apiVersion: apps/v1
kind: Deployment
metadata:
  name: corda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corda
  template:
    metadata:
      labels:
        app: corda
    spec:
      containers:
        - name: corda
          image: corda/corda-os-combined-worker-kafka:5.2.0.0
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: LOG4J_CONFIG_FILE
              value: "config/log4j2.xml"
            - name: CONSOLE_LOG_LEVEL
              value: "info"
            - name: ENABLE_LOG4J2_DEBUG
              value: "false"
          args:
            - "-mbus.busType=KAFKA"
            - "-mbootstrap.servers=kafka:29092"
            - "-spassphrase=password"
            - "-ssalt=salt"
            - "-ddatabase.user=user"
            - "-ddatabase.pass=password"
            - "-ddatabase.jdbc.url=jdbc:postgresql://postgresql:5432/cordacluster"
            - "-ddatabase.jdbc.directory=/opt/jdbc-driver/"
          ports:
            - containerPort: 8888
            - containerPort: 7004
            - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: corda
spec:
  selector:
    app: corda
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
    - protocol: TCP
      port: 7004
      targetPort: 7004
    - protocol: TCP
      port: 5005
      targetPort: 5005