apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-management-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-management-tool
  template:
    metadata:
      labels:
        app: flow-management-tool
    spec:
      containers:
        - name: flow-management-tool
          image: flow-management-tool:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flow-management-tool
spec:
  selector:
    app: flow-management-tool
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000