apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP  # Change to NodePort if external access is needed
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
