apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"  # Expose controller port
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
