apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
  clusterIP: None  # Ensures internal pod-to-pod communication
